### ISSUE TITLE
docker: Error response from daemon: error gathering device information while adding custom device "/dev/snd": no such file or directory.

### ISSUE THREAD

**Issue by lollocavs** [trinhbiendich/snowboy-docker#1]
I try to run the container, but it doesn't work.
My host machine is a Mac. Can somebody help me?

**Comment by sinhsac** [comment]
Hi @lollocavs ,

[this link https://apple.stackexchange.com/questions/47822/where-are-audio-device-files-in-osx ](https://apple.stackexchange.com/questions/47822/where-are-audio-device-files-in-osx) maybe can help you.
in case, the Audio using on xxx maybe just has on Linux. On Mac you need to find "Audio HAL".

Thanks,
Sac Le
